# Generated by Django 6.0.4 on 2026-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='mode',
            field=models.CharField(choices=[('rent', 'Аренда'), ('buy', 'Покупка')], default='rent', max_length=4),
        ),
    ]
